spring:
  datasource:
    username: root
    password: 8681700
    url: jdbc:mysql://192.168.100.2:3306/commodity_trace
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: mysql
  jackson:
    serialization: true
  output:
    ansi:
      enabled: always
  redis:
    host: 192.168.100.2
    port: 6379
    database: 0
server:
  context-path: /api
logging:
  level: debug